USE [master]
GO

/****** Object:  Database [QLSINHVIEN]    Script Date: 10/29/2023 3:33:56 PM ******/
CREATE DATABASE [QLSINHVIEN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLSINHVIEN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QLSINHVIEN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLSINHVIEN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QLSINHVIEN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLSINHVIEN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLSINHVIEN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLSINHVIEN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLSINHVIEN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLSINHVIEN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLSINHVIEN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET RECOVERY FULL 
GO

ALTER DATABASE [QLSINHVIEN] SET  MULTI_USER 
GO

ALTER DATABASE [QLSINHVIEN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLSINHVIEN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLSINHVIEN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLSINHVIEN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLSINHVIEN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLSINHVIEN] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLSINHVIEN] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QLSINHVIEN] SET  READ_WRITE 
GO

